<%@ Page Language="C#" MasterPageFile="~/MasterBTMS.master" AutoEventWireup="true"
    CodeFile="EmpFileReader.aspx.cs" Inherits="EIS_EmpFileReader" Title="Employee Personal File Reader" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

<script language="javascript" type="text/javascript" src="../JScripts/Confirmation.js">
    </script>
    
    
    <div class="formStyle" style="height:640px; width: 950px;">
        <div id="formhead1">
            Employee Personal File Reader</div>
        <div class="MsgBox">
            <asp:Label ID="lblMsg" runat="server" CssClass="msglabel"></asp:Label>
        </div>
       <div style="margin-left:10px;margin-right:10px;margin-top:10px;">
       <fieldset style="margin-left:10px;margin-right:10px;margin-top:10px;">
                                        <table style="width:100%">
                                            <tr>
                                                <td style="width:49%;background-color:#C2D69B;">
                                                    <table>
                                                        <tr>
                                                            <td class="textlevel">
                                                                Node Title (Level 0):
                                                            </td>
                                                            <td style="width:130px">
                                                                <asp:TextBox ID="txtNode" Width="125px" runat="server"></asp:TextBox></td>
                                                            <td align="left">
                                                                <asp:Button ID="btnFind" runat="server" Text="Find" OnClick="btnFind_Click1" Width="65px" /></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td style="width:49%;background-color:#F2DBDB;">
                                                    <table>
                                                        <tr>
                                                             <td class="textlevel">File Name : </td>
                                                             <td><asp:TextBox ID="txtFileName" runat="server"></asp:TextBox></td>   
                                                             <td><asp:Button ID="btnFileDelete" Text="Delete" OnClientClick="javascript:return HistorySaveConfirmation();" runat="server" OnClick="btnFileDelete_Click" /></td>   
                                                             <td><asp:Button ID="btnRefresh" Text="Refresh" runat="server" OnClick="btnRefresh_Click" /></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                          </tr>
                                         </table>
                                      
                                          
                                                      
                                                      <div style="margin-left: 2px;margin-top:5px; height: 500px; overflow: scroll;background-color:#B8CCE4;width:100%;">
                                                        <asp:TreeView ID="MyTree" PathSeparator="|" ExpandDepth="0" runat="server" ImageSet="Arrows"
                                                            AutoGenerateDataBindings="False" OnSelectedNodeChanged="MyTree_SelectedNodeChanged">
                                                            <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px"
                                                                ForeColor="#5555DD"></SelectedNodeStyle>
                                                            <NodeStyle VerticalPadding="0px" Font-Names="Tahoma" Font-Size="10pt" HorizontalPadding="5px"
                                                                ForeColor="Black" NodeSpacing="0px"></NodeStyle>
                                                            <ParentNodeStyle Font-Bold="False" />
                                                            <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD"></HoverNodeStyle>
                                                        </asp:TreeView>
                                                      </div>
                        </fieldset>
        <asp:Label ID="lblPath" runat="server"></asp:Label>
        <asp:Label ID="lblNodeText" runat="server" Visible="False" ForeColor="white"></asp:Label>
    </div>
    </div>
</asp:Content>
